<div class="container">

    <div class="row">
        <div class="col-5">
            <div class="personagemCadastrarPerfil">
                <img src="img/personagens/aqua3Back.jpg" alt="Aqua">
            </div>
        </div>
        <div class="col-6">

            <h2 id="tituloCadastrarPerfil">Cadastrar Perfil</h2>

            <div class="formCadastrarPerfil">
                <form action="">
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com">
                        <label for="floatingInput">Usuário</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                        <label for="floatingInput">E-mail</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
                        <label for="floatingPassword">Senha</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
                        <label for="floatingPassword">Repita a sua Senha</label>
                    </div>
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-outline blue btn-block">Cadastrar </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>