<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <div class="card" style="width: 36rem;">
            <div class="card-body">

                <div class="d-flex justify-content-center">
                    <img src="/img/personagens/sucesso.gif" style="border-radius:10px" />
                </div>

                <div class="row">
                    <div class="col">
                        <h2 class="tituloFormat">Cadastro realizado com sucesso</h2>
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <div class="d-grid gap-2">
                            <button type="button" onclick="location.href='/'"
                                class="btn btn-outline blue btn-block">Clique aqui para fazer login!</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>