<!--    <img src="img/vivi.png" alt="vivi" id="vivi">
 -->
<div class="container-fluid" id="containerPrincipalBTN">
    <div class="container" id="containerBTN">
        <div class="row">
            <H1 id="tituloPrincipalHome">Seja Bem-Vindo!!!</H1>
            <div class="col">
                <div class="d-grid animationButton">
                    <button type="button" class="btn btn-outline blue btn-block" id="noticias"
                        onclick="window.location.href='Site/pages/noticias.php'">
                        Noticias
                    </button>
                </div>
            </div>
            <div class="col">
                <div class="d-grid animationButton">
                    <button type="button" class="btn btn-outline blue btn-block" id="mangas"
                        onclick="window.location.href='Site/pages/manga.php'">
                        Ler Mangás
                    </button>
                </div>
            </div>
            <div class="col">
                <div class="d-grid animationButton">
                    <button type="button" class="btn btn-outline blue btn-block" id="loja"
                        onclick="window.location.href='Site/pages/loja.php'">
                        Loja
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>