<!--    <img src="img/vivi.png" alt="vivi" id="vivi">
 -->
<div class="container-fluid" id="containerPrincipalBTN">
    <div class="container" id="containerBTN">
        <div class="row">
            <H1 id="tituloPrincipalHome">Seja Bem-Vindo!!!</H1>
            <div class="col">
                <div class="d-grid animationButton">
                    <button type="button" class="btn btn-outline blue btn-block" id="noticias"
                        onclick="window.location.href='Site/pages/noticias.php'">
                        Noticias
                    </button>
                </div>
            </div>
            <div class="col">
                <div class="d-grid animationButton">
                    <button type="button" class="btn btn-outline blue btn-block" id="mangas"
                        onclick="window.location.href='Site/pages/manga.php'">
                        Ler Mangás
                    </button>
                </div>
            </div>
            <div class="col">
                <div class="d-grid animationButton">
                    <button type="button" class="btn btn-outline blue btn-block" id="loja"
                        onclick="window.location.href='Site/pages/loja.php'">
                        Loja
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">

    <form action="/autenticar" class="row g-2" style="justify-content:center" method="POST">
        <div class="col-auto">
            <h2 class="tituloFormat">Efetuar Login</h2>
        </div>
        <div class="col-auto inputsHome">
            <input type="text" class="form-control" name="emailAutenticar" id="emailAutenticar"
                placeholder="Insira o seu Email">
        </div>
        <div class="col-auto inputsHome">
            <input type="password" class="form-control" name="senhaAutenticar" id="senhaAutenticar"
                placeholder="Digite a sua Senha">
        </div>
        <div class="col-auto inputsHome">
            <button type="submit" class="btn btn-outline blue btn-block">Entrar</button>
        </div>
        <?php if($this->view->login == 'erro') {?>
        <div class=" container">
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                Email ou Senha Inválido(s)
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
        <?php
        }?>

    </form>

</div>