<div class="container mt-5">

    <div class="row pt-2">
        <div class="col-md-3">
            <div class="perfil">

                <div class="perfilTopo">

                </div>

                <div class="perfilPainel">
                    <div class="row mt-2 mb-2">
                        <div class="col mb-2">
                            <span class="perfilPainelNome">Nome do Usuário</span>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col">
                            <span class="perfilPainelItem">Comentários</span><br />
                            <span class="perfilPainelItemValor">0</span>
                        </div>

                        <div class="col">
                            <span class="perfilPainelItem">Seguindo</span><br />
                            <span class="perfilPainelItemValor">0</span>
                        </div>

                        <div class="col">
                            <span class="perfilPainelItem">Seguidores</span><br />
                            <span class="perfilPainelItemValor">0</span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="d-grid gap-2">
                <button type="button" class="btn btn-outline-danger" onClick="window.open('/sair');">Sair</button>
            </div>
        </div>

        <div class="col-md-6">
            <div class="row mb-2">
                <div class="col comentarioBox">
                    <form method="post" action="/comentario">
                        <textarea class="form-control" name="comentario" id="exampleFormControlTextarea1"
                            rows="3"></textarea>

                        <div class="col mt-2 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Comentar</button>
                        </div>

                    </form>
                </div>
            </div>

            <?php foreach($this->view->comentarios as $id => $comentario){?>
            <div class="row comentario">
                <div class="col">
                    <p>
                        <strong>
                            <?=$comentario['nome']?>
                        </strong>
                        <small>
                            <span class="text text-muted">
                                - <?=$comentario['data']?>
                            </span>
                        </small>
                    </p>

                    <p>
                        <?=$comentario['comentario']?>
                    </p>
                    <?php if($comentario['id_usuario'] == $_SESSION['id']){?>
                    <div class="col d-flex justify-content-end">
                        <a href="/removerComentario?id=<?=$comentario['id']?>" class="btn btn-danger">Remover</a>
                    </div>

                    <?php } ?>
                </div>
            </div>
            <?php
            }
            ?>

        </div>


        <div class="col-md-3">
            <div class="quemSeguir">
                <span class="quemSeguirTitulo">Quem seguir</span><br />
                <hr />
                <a href="/quemSeguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
            </div>
        </div>

    </div>
</div>